In [151]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Input DNA dataset

In [152]:
dna_df = pd.read_csv("E:\研究生\EECS 6690\codon_usage.csv")
dna_df

C:\Users\11518\AppData\Local\Temp\ipykernel_12084\3409277544.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dna_df = pd.read_csv("E:\研究生\EECS 6690\codon_usage.csv")

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.0218,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13023,pri,0,9601,1097,Pongo pygmaeus abelii,0.02552,0.03555,0.00547,0.01367,0.01276,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13024,pri,1,9601,2067,mitochondrion Pongo pygmaeus abelii,0.01258,0.03193,0.01984,0.00629,0.01451,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13025,pri,1,9602,1686,mitochondrion Pongo pygmaeus pygmaeus,0.01423,0.03321,0.01661,0.00356,0.01127,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13026,pri,0,9606,40662582,Homo sapiens,0.01757,0.02028,0.00767,0.01293,0.01319,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13027,pri,1,9606,8998998,mitochondrion Homo sapiens,0.01778,0.03724,0.01732,0.00600,0.01689,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

# Missing value check

In [153]:
def missing_cols(df):
    '''prints out columns with its amount of missing values'''
    total = 0
    for col in df.columns:
        missing_vals = df[col].isnull().sum()
        total += missing_vals
        if missing_vals != 0:
            print(f"{col} => {df[col].isnull().sum()}")
    
    if total == 0:
        print("no missing values left")
            
missing_cols(dna_df)

no missing values left

# Data cleaning

In [154]:
dna_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13028 entries, 0 to 13027
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Kingdom      13028 non-null  object
 1   DNAtype      13028 non-null  int64
 2   SpeciesID    13028 non-null  int64
 3   Ncodons      13028 non-null  int64
 4   SpeciesName  13028 non-null  object
 5   UUU          13028 non-null  object
 6   UUC          13028 non-null  object
 7   UUA          13028 non-null  float64
 8   UUG          13028 non-null  float64
 9   CUU          13028 non-null  float64
 10  CUC          13028 non-null  float64
 11  CUA          13028 non-null  float64
 12  CUG          13028 non-null  float64
 13  AUU          13028 non-null  float64
 14  AUC          13028 non-null  float64
 15  AUA          13028 non-null  float64
 16  AUG          13028 non-null  float64
 17  GUU          13028 non-null  float64
 18  GUC          13028 non-null  float64
 19  GUA          13028 non-null  float64
 20  GUG          13028 non-null  float64
 21  GCU          13028 non-null  float64
 22  GCC          13028 non-null  float64
 23  GCA          13028 non-null  float64
 24  GCG          13028 non-null  float64
 25  CCU          13028 non-null  float64
 26  CCC          13028 non-null  float64
 27  CCA          13028 non-null  float64
 28  CCG          13028 non-null  float64
 29  UGG          13028 non-null  float64
 30  GGU          13028 non-null  float64
 31  GGC          13028 non-null  float64
 32  GGA          13028 non-null  float64
 33  GGG          13028 non-null  float64
 34  UCU          13028 non-null  float64
 35  UCC          13028 non-null  float64
 36  UCA          13028 non-null  float64
 37  UCG          13028 non-null  float64
 38  AGU          13028 non-null  float64
 39  AGC          13028 non-null  float64
 40  ACU          13028 non-null  float64
 41  ACC          13028 non-null  float64
 42  ACA          13028 non-null  float64
 43  ACG          13028 non-null  float64
 44  UAU          13028 non-null  float64
 45  UAC          13028 non-null  float64
 46  CAA          13028 non-null  float64
 47  CAG          13028 non-null  float64
 48  AAU          13028 non-null  float64
 49  AAC          13028 non-null  float64
 50  UGU          13028 non-null  float64
 51  UGC          13028 non-null  float64
 52  CAU          13028 non-null  float64
 53  CAC          13028 non-null  float64
 54  AAA          13028 non-null  float64
 55  AAG          13028 non-null  float64
 56  CGU          13028 non-null  float64
 57  CGC          13028 non-null  float64
 58  CGA          13028 non-null  float64
 59  CGG          13028 non-null  float64
 60  AGA          13028 non-null  float64
 61  AGG          13028 non-null  float64
 62  GAU          13028 non-null  float64
 63  GAC          13028 non-null  float64
 64  GAA          13028 non-null  float64
 65  GAG          13028 non-null  float64
 66  UAA          13028 non-null  float64
 67  UAG          13028 non-null  float64
 68  UGA          13028 non-null  float64
dtypes: float64(62), int64(3), object(4)
memory usage: 6.9+ MB

In [155]:
for i in range(len(dna_df)):
    x = dna_df.iloc[:, 5][i]
    if isinstance(x, str):
        r = x.replace('.', '', 1).isdigit()
        if r == False:
            print("The index of the non-int or non-float entry:")
            print(i)
            print("The value of that entry:")
            print(dna_df.iloc[:, 5][i])
            print("--------------------------------------------")

The index of the non-int or non-float entry:
486
The value of that entry:
non-B hepatitis virus
--------------------------------------------
The index of the non-int or non-float entry:
5063
The value of that entry:
12;I
--------------------------------------------

In [156]:
for i in range(len(dna_df)):
    x = dna_df.iloc[:, 6][i]
    if isinstance(x, str):
        r = x.replace('.', '', 1).isdigit()
        if r == False:
            print("The index of the non-int or non-float entry:")
            print(i)
            print("The value of that entry:")
            print(dna_df.iloc[:, 6][i])
            print("--------------------------------------------")

The index of the non-int or non-float entry:
5063
The value of that entry:
-
--------------------------------------------

In [157]:
dna_df.shape

(13028, 69)

In [158]:
dna_df = dna_df.drop(486).drop(5063)
dna_df['UUU'] = pd.to_numeric(dna_df['UUU'])
dna_df['UUC'] = pd.to_numeric(dna_df['UUC'])
dna_df.shape

(13026, 69)

In [159]:
dna_df

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.02180,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13023,pri,0,9601,1097,Pongo pygmaeus abelii,0.02552,0.03555,0.00547,0.01367,0.01276,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13024,pri,1,9601,2067,mitochondrion Pongo pygmaeus abelii,0.01258,0.03193,0.01984,0.00629,0.01451,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13025,pri,1,9602,1686,mitochondrion Pongo pygmaeus pygmaeus,0.01423,0.03321,0.01661,0.00356,0.01127,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13026,pri,0,9606,40662582,Homo sapiens,0.01757,0.02028,0.00767,0.01293,0.01319,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13027,pri,1,9606,8998998,mitochondrion Homo sapiens,0.01778,0.03724,0.01732,0.00600,0.01689,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [160]:
from sklearn import preprocessing
dna_df['Kingdom'] = preprocessing.LabelEncoder().fit_transform(dna_df['Kingdom'])
corr_dna_df = pd.DataFrame({'Kingdom': dna_df['Kingdom']})
dna_df['Kingdom']

0        9
1        9
2        9
3        9
4        9
        ..
13023    7
13024    7
13025    7
13026    7
13027    7
Name: Kingdom, Length: 13026, dtype: int32

In [161]:
dna_df = dna_df.drop(columns=['SpeciesName'])

In [162]:
dna_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13026 entries, 0 to 13027
Data columns (total 68 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Kingdom    13026 non-null  int32
 1   DNAtype    13026 non-null  int64
 2   SpeciesID  13026 non-null  int64
 3   Ncodons    13026 non-null  int64
 4   UUU        13026 non-null  float64
 5   UUC        13026 non-null  float64
 6   UUA        13026 non-null  float64
 7   UUG        13026 non-null  float64
 8   CUU        13026 non-null  float64
 9   CUC        13026 non-null  float64
 10  CUA        13026 non-null  float64
 11  CUG        13026 non-null  float64
 12  AUU        13026 non-null  float64
 13  AUC        13026 non-null  float64
 14  AUA        13026 non-null  float64
 15  AUG        13026 non-null  float64
 16  GUU        13026 non-null  float64
 17  GUC        13026 non-null  float64
 18  GUA        13026 non-null  float64
 19  GUG        13026 non-null  float64
 20  GCU        13026 non-null  float64
 21  GCC        13026 non-null  float64
 22  GCA        13026 non-null  float64
 23  GCG        13026 non-null  float64
 24  CCU        13026 non-null  float64
 25  CCC        13026 non-null  float64
 26  CCA        13026 non-null  float64
 27  CCG        13026 non-null  float64
 28  UGG        13026 non-null  float64
 29  GGU        13026 non-null  float64
 30  GGC        13026 non-null  float64
 31  GGA        13026 non-null  float64
 32  GGG        13026 non-null  float64
 33  UCU        13026 non-null  float64
 34  UCC        13026 non-null  float64
 35  UCA        13026 non-null  float64
 36  UCG        13026 non-null  float64
 37  AGU        13026 non-null  float64
 38  AGC        13026 non-null  float64
 39  ACU        13026 non-null  float64
 40  ACC        13026 non-null  float64
 41  ACA        13026 non-null  float64
 42  ACG        13026 non-null  float64
 43  UAU        13026 non-null  float64
 44  UAC        13026 non-null  float64
 45  CAA        13026 non-null  float64
 46  CAG        13026 non-null  float64
 47  AAU        13026 non-null  float64
 48  AAC        13026 non-null  float64
 49  UGU        13026 non-null  float64
 50  UGC        13026 non-null  float64
 51  CAU        13026 non-null  float64
 52  CAC        13026 non-null  float64
 53  AAA        13026 non-null  float64
 54  AAG        13026 non-null  float64
 55  CGU        13026 non-null  float64
 56  CGC        13026 non-null  float64
 57  CGA        13026 non-null  float64
 58  CGG        13026 non-null  float64
 59  AGA        13026 non-null  float64
 60  AGG        13026 non-null  float64
 61  GAU        13026 non-null  float64
 62  GAC        13026 non-null  float64
 63  GAA        13026 non-null  float64
 64  GAG        13026 non-null  float64
 65  UAA        13026 non-null  float64
 66  UAG        13026 non-null  float64
 67  UGA        13026 non-null  float64
dtypes: float64(64), int32(1), int64(3)
memory usage: 6.8 MB

In [163]:
dna_df.to_csv('codon_usage_clean.csv')

# Naive Bayes Model

In [164]:
from sklearn.preprocessing import MinMaxScaler
dna_df_updated1 = dna_df
y1 = dna_df_updated1['DNAtype']
x1 = dna_df_updated1.drop(columns=['DNAtype'])
scaler = MinMaxScaler( )
x1_scaled = scaler.fit_transform(x1)
x1_scaled

array([[9.00000000e-01, 2.15340051e-01, 2.44702727e-05, ...,
        5.55309735e-02, 1.95236236e-02, 0.00000000e+00],
       [9.00000000e-01, 2.15346497e-01, 1.16571952e-05, ...,
        5.99557522e-02, 2.65521281e-02, 0.00000000e+00],
       [9.00000000e-01, 2.16496152e-01, 9.49790886e-05, ...,
        8.65044248e-02, 0.00000000e+00, 1.34957826e-02],
       ...,
       [7.00000000e-01, 2.06185789e-02, 1.68709619e-05, ...,
        7.87610619e-02, 4.64662241e-02, 1.89034677e-01],
       [7.00000000e-01, 2.06271744e-02, 1.00000000e+00, ...,
        2.19026549e-02, 3.08473253e-02, 1.46204311e-02],
       [7.00000000e-01, 2.06271744e-02, 2.21289914e-01, ...,
        3.45132743e-02, 4.45138618e-02, 2.02530459e-01]])

In [170]:
dna_df_updated2 = dna_df
y2 = dna_df_updated2['Kingdom']
x2 = dna_df_updated2.drop(columns=['Kingdom', 'DNAtype','SpeciesID', 'Ncodons'])
x2_scaled = x2.to_numpy()
x2_scaled

array([[0.01654, 0.01203, 0.0005 , ..., 0.00251, 0.0005 , 0.     ],
       [0.02714, 0.01357, 0.00068, ..., 0.00271, 0.00068, 0.     ],
       [0.01974, 0.0218 , 0.01357, ..., 0.00391, 0.     , 0.00144],
       ...,
       [0.01423, 0.03321, 0.01661, ..., 0.00356, 0.00119, 0.02017],
       [0.01757, 0.02028, 0.00767, ..., 0.00099, 0.00079, 0.00156],
       [0.01778, 0.03724, 0.01732, ..., 0.00156, 0.00114, 0.02161]])

In [172]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1_scaled, y1, test_size=0.20, random_state=20)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2_scaled, y2, test_size=0.20, random_state=20)
print(x1_train.shape, x1_test.shape, y1_train.shape, y1_test.shape)

(10420, 67) (2606, 67) (10420,) (2606,)

In [167]:
from sklearn.naive_bayes import GaussianNB
gnb1 = GaussianNB()
gnb1.fit(x1_train, y1_train)

GaussianNB()

In [168]:
from sklearn.metrics import accuracy_score
y1_pred = gnb1.predict(x1_test)
acc1 = accuracy_score(y1_test, y1_pred)
print("accuracy_score: ",acc1)

accuracy_score:  0.9240214888718342

In [173]:
from sklearn.naive_bayes import MultinomialNB
gnb2 = GaussianNB()
gnb2.fit(x2_train, y2_train)
y2_pred = gnb2.predict(x2_test)
acc2 = accuracy_score(y2_test, y2_pred)
print("accuracy_score: ",acc)

accuracy_score:  0.9240214888718342